"""empty message

Revision ID: a66e1eed47f0
Revises: 5c4a1799aadd
Create Date: 2020-03-08 20:05:51.745749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66e1eed47f0'
down_revision = '5c4a1799aadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('location', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Artist', 'Location', ['location'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'location')
    # ### end Alembic commands ###
